services:
  influxdb:
    image: influxdb:${INFLUXDB_VERSION}
    container_name: influxdbCS
    restart: unless-stopped
    ports:
      - "${INFLUXDB_PORT}:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}

  mariadb:
    image: mariadb:${MARIADB_VERSION}
    container_name: mariadbCS
    restart: unless-stopped
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - mariadb_data:/var/lib/mysql

  gateway:
    image: nginx:alpine
    container_name: gatewayCS
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:80"
    volumes:
      - ./nginx/gateway.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUXDB_ORG}
      - INFLUX_BUCKET=${INFLUXDB_BUCKET}
    depends_on:
      - mariadb

  frontend:
    restart: unless-stopped
    build:
      context: ./angular
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - influxdb

  adminer:
    image: adminer:latest
    container_name: adminerCS
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT}:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    depends_on:
      - mariadb

  grafana:
    image: grafana/grafana:latest
    container_name: grafanaCS
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  mariadb_data:
  grafana_data: