services:
  influxdb:
    image: influxdb:${INFLUXDB_VERSION}
    container_name: influxdbCS
    ports:
      - "${INFLUXDB_PORT}:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}

  mariadb:
    image: mariadb:${MARIADB_VERSION}
    container_name: mariadbCS
    restart: always
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql

  nginx:
    container_name: nginxCS
    build:
      context: ./angular
      dockerfile: Dockerfile
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - mariadb
      - influxdb

  backend:
    build: ./backend
    container_name: backendCS
    ports:
      - "${BACKEND_PORT}:3000"
    depends_on:
      - mariadb

volumes:
  influxdb_data:
  mariadb_data:
